[package]
name = "tol"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
walkdir = "2.5.0"
anyhow = "1.0.94"
indicatif = "0.17.9"
